def create_document() -> int: ...
def open_document(path: str) -> int: ...
def edit_document(path: str) -> int: ...
def save_document(handle: int, path: str) -> None: ...
def dispose(handle: int) -> None: ...
def get_int(handle: int, name: str) -> int: ...
def set_int(handle: int, name: str, value: int) -> None: ...
def get_float(handle: int, name: str) -> float: ...
def set_float(handle: int, name: str, value: float) -> None: ...
def get_str(handle: int, name: str) -> str: ...
def set_str(handle: int, name: str, value: str) -> None: ...
def get_count(handle: int, collection: str) -> int: ...
def get_child_handle(handle: int, collection: str, index: int) -> int: ...
def append_child(handle: int, child_type: str) -> int: ...
def remove_child(handle: int) -> None: ...
def get_element_type(handle: int) -> str: ...
def add_table(doc_handle: int, rows: int, cols: int) -> int: ...
def add_image(parent_handle: int, data: bytes, content_type: str, width_emu: int, height_emu: int) -> int: ...
def get_image_data(handle: int) -> bytes: ...
