import os
from collections.abc import Sequence
from pathlib import Path
from typing import IO, Self

from navyfox._block import BlockContainerMixin
from navyfox._collection import CollectionMixin as _CollectionMixin
from navyfox._collection import DocumentView as DocumentView
from navyfox._proxy.base import Element as _Element
from navyfox.formats import PageMargins
from navyfox.image import Image
from navyfox.paragraph import HorizontalRule, LineStyleArg, Paragraph
from navyfox.section import Section
from navyfox.styles import Style, StyleCollection
from navyfox.table import Table

_PathArg = str | os.PathLike[str] | IO[bytes]

class Document(BlockContainerMixin, _CollectionMixin[_Element]):
    def __init__(self) -> None: ...
    @classmethod
    def open(cls, path: _PathArg) -> Document: ...
    @classmethod
    def edit(cls, path: _PathArg) -> Document: ...
    @property
    def is_open(self) -> bool: ...
    @property
    def path(self) -> str | None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *_: object) -> None: ...
    def save(self, path: _PathArg | None = None) -> None: ...
    @property
    def styles(self) -> StyleCollection: ...
    @property
    def default_style(self) -> Style | None: ...
    @property
    def author(self) -> str: ...
    @author.setter
    def author(self, value: str) -> None: ...
    @property
    def title(self) -> str: ...
    @title.setter
    def title(self, value: str) -> None: ...
    @property
    def subject(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def language(self) -> str: ...
    @property
    def page_count(self) -> int: ...
    @property
    def sections(self) -> DocumentView[Section]: ...
    @property
    def margins(self) -> PageMargins: ...
    @margins.setter
    def margins(
        self,
        value: PageMargins | float | tuple[float, float] | tuple[float, float, float, float],
    ) -> None: ...
    def group[T: _Element](self, types: Sequence[type[T]]) -> DocumentView[T]: ...
    def add_paragraph(self, text: str = ..., style: str = ...) -> Paragraph: ...
    def add_heading(self, text: str = ..., level: int = ...) -> Paragraph: ...
    def add_table(self, rows: int, cols: int, style: str = ...) -> Table: ...
    def add_horizontal_rule(
        self,
        *,
        line_style: LineStyleArg = ...,
        line_width: float = ...,
        line_color: str = ...,
    ) -> HorizontalRule: ...
    def add_bullet(self, text: str = ..., level: int = ...) -> Paragraph: ...
    def add_numbered(self, text: str = ..., level: int = ...) -> Paragraph: ...
    def add_image(
        self,
        src: str | Path | None = ...,
        *,
        data: bytes | None = ...,
        content_type: str | None = ...,
        width: float = ...,
        height: float = ...,
        alt_text: str = ...,
    ) -> Image: ...
    def __bool__(self) -> bool: ...
    def __contains__(self, element: object) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
