from collections.abc import Iterator
from pathlib import Path
from typing import Any, Literal, overload

from navyfox._collection import DocumentView as DocumentView
from navyfox._proxy.base import ProxyBase as _ProxyBase
from navyfox.image import Image
from navyfox.paragraph import HorizontalRule, LineStyleArg, Paragraph

class Cell(_ProxyBase):
    text: str
    width: float
    vertical_alignment: Literal["top", "center", "bottom"]
    merge_up: str
    merge_left: str

    @property
    def paragraphs(self) -> DocumentView[Paragraph]: ...
    @property
    def tables(self) -> DocumentView[Table]: ...
    def add_paragraph(self, text: str = ..., style: str = ...) -> Paragraph: ...
    def add_heading(self, text: str = ..., level: int = ...) -> Paragraph: ...
    def add_table(self, rows: int, cols: int, style: str = ...) -> Table: ...
    def add_horizontal_rule(
        self,
        *,
        line_style: LineStyleArg = ...,
        line_width: float = ...,
        line_color: str = ...,
    ) -> HorizontalRule: ...
    def add_bullet(self, text: str = ..., level: int = ...) -> Paragraph: ...
    def add_numbered(self, text: str = ..., level: int = ...) -> Paragraph: ...
    def add_image(
        self,
        src: str | Path | None = ...,
        *,
        data: bytes | None = ...,
        content_type: str | None = ...,
        width: float = ...,
        height: float = ...,
        alt_text: str = ...,
    ) -> Image: ...
    def merge(self, other: Cell) -> None: ...
    def copy(self) -> Cell: ...
    def _copy_data(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Paragraph | Table]: ...

class Row(_ProxyBase):
    height: float
    height_rule: Literal["auto", "exact", "atLeast"]
    is_header: bool
    cant_split: bool

    @property
    def cells(self) -> DocumentView[Cell]: ...
    def copy(self) -> Row: ...
    def _copy_data(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Cell]: ...
    def __getitem__(self, index: int) -> Cell: ...

class Table(_ProxyBase):
    style: str
    alignment: Literal["left", "center", "right"] | None
    width: float
    indent: float
    cell_spacing: float

    def __init__(
        self,
        rows: int,
        cols: int,
        *,
        style: str = ...,
    ) -> None: ...
    @property
    def rows(self) -> DocumentView[Row]: ...
    @property
    def cells(self) -> DocumentView[Cell]: ...
    @property
    def data(self) -> Iterator[list[str]]: ...
    def cell(self, row: int, col: int) -> Cell: ...
    def copy(self) -> Table: ...
    def _copy_data(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Row]: ...
    def __contains__(self, row: object) -> bool: ...
    @overload
    def __getitem__(self, index: int) -> Row: ...
    @overload
    def __getitem__(self, index: tuple[int, int]) -> Cell: ...
